#!/bin/bash

docker build -t monty-$BUILD_NUMBER docker/

cleanup(){
  docker rmi monty-$BUILD_NUMBER
  exit
}

trap cleanup SIGINT SIGQUIT ERR

docker run --rm -t monty-$BUILD_NUMBER docker/runtests

cleanup

