#!/bin/bash -xe

#echo "${DB_PORT_5432_TCP_ADDR}:${DB_PORT_5432_TCP_PORT}:postgres:${DB_ENV_USER}:${DB_ENV_PASS}" > $HOME/.pgpass

#dropdb monty
#createdb monty

revel test github.com/hackerlist/monty

